<a href="https://colab.research.google.com/github/Mrkoi2002/AI/blob/main/ANN_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gọi các thư viện
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import seaborn as sas
import pandas as pd
import  numpy as np
from sklearn.linear_model import LinearRegression


In [ ]:
iris = datasets.load_iris()


In [ ]:
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)
X_test_std = SC.transform(X_test)

regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test).round(1)

calculation = pd.DataFrame(np.c_[y_test, y_pred], columns = ['Original Price','Predicted Price'])
print('Do chinh xac cua train:',regressor.score(X_train, y_train))
print('Do chinh xac cua test:',regressor.score(X_test, y_test))
     




Do chinh xac cua train: 0.9400414125603199
Do chinh xac cua test: 0.9068709133002238


In [ ]:
model = Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình:',accuracy_score(y_test,y_pred))




[2 1 0 2 0 0 1 0 2 1 1 0 1 2 2 0 0 2 2 1 1 0 1 2 0 1 0 2 0 2 0 2 1 0 2 1 0
 2 2 2 0 1 2 1 1]
[2 1 0 1 0 0 2 0 2 1 1 0 1 2 2 0 0 2 2 1 1 0 1 1 0 1 0 2 0 2 0 2 1 0 2 0 0
 1 2 1 0 1 2 2 1]
Độ chính xác của mô hình: 0.8444444444444444
